library(Seurat)
library(dplyr)
library(patchwork)
library(matrixStats)
library(aws.s3)
library(sjmisc)
library(parallel)
library(Giotto)

setwd("C:/Users/alexa/R_testbed")
# Object Referencing/Pointing (hacking)
#source(paste0(getwd(),"/ObjectReferencing.R"))
#source(paste0(getwd(),"/SeuratIntro.R"))
source(paste0(getwd(),"/AWSAccess.R"))
